proStage_ps:
    path: /pro/stage
    controller: App\Controller\ProStageController::index

proStage_accueil:
    path: /
    controller: App\Controller\ProStageController::afficheBienvenue

proStage_formations:
    path: /formations
    controller: App\Controller\ProStageController::afficheFormations

proStage_formations_id:
    path: /formations/{nom}
    controller: App\Controller\ProStageController::formations

proStage_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::afficheEntreprises

proStage_entreprises_id:
    path: /entreprises/{nom}
    controller: App\Controller\ProStageController::entreprises

proStage_stages_id:
    path: /stages/{id}
    controller: App\Controller\ProStageController::afficheId

proStage_ajoutEntreprise:
    path: admin/entreprise/ajouter
    controller: App\Controller\ProStageController::ajouterEntreprise

proStage_modifierEntreprise:
    path: admin/entreprises/modif/{nom}
    controller: App\Controller\ProStageController::modifierEntreprise

proStage_ajoutStage:
    path: user/stage/ajouter
    controller: App\Controller\ProStageController::ajouterStage

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_inscription:
    path: /inscription
    controller: App\Controller\SecurityController::inscription
